name: Auto Tweet
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          TW_API_KEY: ${{ secrets.TW_API_KEY }}
          TW_API_SECRET: ${{ secrets.TW_API_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
          TW_BEARER_TOKEN: ${{ secrets.TW_BEARER_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
